/*
 * Warung Makan
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type CustomerBody struct {
	Id string `json:"id"`
	Name string `json:"name"`
	Email string `json:"email"`
	Address string `json:"address"`
}
